# Generated by Django 4.2.16 on 2024-12-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwm", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apk",
            options={"verbose_name": "gwm_apk", "verbose_name_plural": "gwm_apks"},
        ),
        migrations.AddField(
            model_name="apk",
            name="locked",
            field=models.BooleanField(default=True),
        ),
    ]
