# Generated by Django 4.2.16 on 2024-12-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwm", "0002_alter_apk_options_apk_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apk",
            name="locked",
            field=models.BooleanField(default=False),
        ),
    ]
