# Generated by Django 4.2.16 on 2024-12-17 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gwm", "0003_alter_apk_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apk",
            name="file_url",
            field=models.TextField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
