# Generated by Django 4.2.16 on 2024-12-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwm", "0004_alter_apk_file_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apk",
            name="file_md5",
        ),
        migrations.AlterField(
            model_name="apk",
            name="status",
            field=models.CharField(
                choices=[("public", "Public"), ("draft", "Draft")],
                default="draft",
                max_length=10,
            ),
        ),
    ]
