# Generated by Django 4.2.16 on 2024-12-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwm", "0007_alter_apk_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apk",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
