# Generated by Django 4.2.16 on 2024-12-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gwm", "0008_alter_apk_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apk",
            name="depended_upon",
        ),
    ]
