# Generated by Django 4.2.16 on 2024-12-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwm", "0010_apk_file_size_alter_apk_describe_alter_apk_file_md5"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apk",
            name="file_size",
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
